SchoolNotification/SchoolNotification/Controllers/CancellationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using SchoolNotification.Models;
using SchoolNotification.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Net;
using WebMatrix.WebData;
using System.Web.Security;

namespace SchoolNotification.Controllers
{
    [Authorize]
    public class CancellationController : Controller
    {
        private DataContext dc = new DataContext();
        private RepoCancellation can = new RepoCancellation();
        private RepoFaculty fac = new RepoFaculty();
        private RepoCourse course = new RepoCourse();

        [Authorize(Roles = "Admin, Faculty, Student")]
        public ActionResult Index()
        {
            var currentUserName = User.Identity.Name;
            var roles = (SimpleRoleProvider)Roles.Provider;
            //var searchStr = "";
            var searchStr = Request.QueryString["SearchString"];
            System.Diagnostics.Debug.WriteLine("Cancellation Controller Index searchStr: " + searchStr+";");
            if (currentUserName != "")
            {
                try
                {
                    if (roles.GetRolesForUser(currentUserName).Contains("Admin"))
                    {
                        ViewBag.adminView = "Y";
                        //System.Diagnostics.Debug.WriteLine("Here");
                        if (searchStr == null)
                        {
                            ViewBag.canlist = can.getListOfCancellationBase();
                        }
                        else
                        {
                            ViewBag.canlist = can.searchListOfCancellationBase(searchStr);
                        }
                    }
                    else if (roles.GetRolesForUser(currentUserName).Contains("Faculty"))
                    {
                        ViewBag.facultyView = "Y";
                        System.Diagnostics.Debug.WriteLine("cancellation.Faculty Name: " + User.Identity.Name);
                        var currentUser = dc.Faculties.FirstOrDefault(n => n.UserName == User.Identity.Name);
                        System.Diagnostics.Debug.WriteLine("cancellation Controller Faculty Id: " + currentUser.UserId);
                        ViewBag.canlist = can.getListOfCancellationForFaculty(currentUser.UserId);
                    }
                    else if (roles.GetRolesForUser(currentUserName).Contains("Student"))
                    {
                        ViewBag.studentView = "Y";
                        var currentUserId = WebSecurity.GetUserId(User.Identity.Name);
                        System.Diagnostics.Debug.WriteLine("cancellation Controller Student Id: " + currentUserId);
                        var canlist = can.getListOfCancellationBaseForStd(currentUserId);
                        if(canlist.Count() != 0){
                            ViewBag.viewcan = true;
                            ViewBag.canlist = canlist;
                        } 
                        
                    }
                }
                catch (Exception e)
                {
                    ViewBag.ExceptionMessage = e.Message;
                    return View("Error");
                }
            }
            return View(); 
        }

        [Authorize(Roles="Admin")]
        [HttpPost]
        public string Index(FormCollection fc, string searchString)
        {
            return "<h3> From [HttpPost]Index: " + searchString + "</h3>";
        }

        [Authorize(Roles = "Admin, Faculty, Student")]
        public ActionResult Details(int? id)
        {
            var currentUserName = User.Identity.GetUserName();
            var roles = (SimpleRoleProvider)Roles.Provider;
            if (roles.GetRolesForUser(currentUserName).Contains("Admin"))
            {
                ViewBag.adminView = "Y";
            }
            else if (roles.GetRolesForUser(currentUserName).Contains("Faculty"))
            {
                ViewBag.facultyView = "Y";
            }
            if(id== null){
                ViewBag.ExceptionMessage ="Invalid Id";
            }
            ViewBag.id = id;
            return View(can.getCancellationFull(id));
        }
        [Authorize(Roles = "Admin,Faculty")]
        public ActionResult Create()
        {
            var currentUserName = User.Identity.GetUserName();
            var currentUserId = WebSecurity.GetUserId(User.Identity.Name);
            var roles = (SimpleRoleProvider)Roles.Provider;
            if (roles.GetRolesForUser(currentUserName).Contains("Admin"))
            {
                ViewBag.adminView = "Y";
                ViewBag.courses = course.getCourseSelectList();
                ViewBag.faculties = fac.getFacultySelectList();
            }
            else if (roles.GetRolesForUser(currentUserName).Contains("Faculty"))
            {
                ViewBag.facultyView = "Y";
                ViewBag.courses = course.getCourseSelectListForFaculty(currentUserId);
            }
            ViewModels.CancellationCreate newItem = new ViewModels.CancellationCreate();           
            ViewBag.dates = can.getDatesSelectList();
            return View(newItem);
        }
        [Authorize(Roles = "Admin, Faculty")]
        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            var currentUserName = User.Identity.GetUserName();
            var currentUserId = WebSecurity.GetUserId(User.Identity.Name);
            var roles = (SimpleRoleProvider)Roles.Provider;
            string facId = "";
            if(ModelState.IsValid)
            {
                try
                {
                    System.Diagnostics.Debug.WriteLine("form count: "+form.Count);
                    if (roles.GetRolesForUser(currentUserName).Contains("Admin"))
                    {
                        if (form.Count == 6)
                        {
                            System.Diagnostics.Debug.WriteLine("form[0]" + form[0]);
                            System.Diagnostics.Debug.WriteLine("form[1]" + form[1]);
                            System.Diagnostics.Debug.WriteLine("form[2]" + form[2]);
                            System.Diagnostics.Debug.WriteLine("form[3]" + form[3]);
                            System.Diagnostics.Debug.WriteLine("form[4]" + form[4]);
                            System.Diagnostics.Debug.WriteLine("form[5]" + form[5]);

                            System.Diagnostics.Debug.WriteLine("Admin create cancellation form[5].ToString().IndexOf('(')" + form[5].ToString().IndexOf("("));
                            System.Diagnostics.Debug.WriteLine("Admin create cancellation form[5].ToString().IndexOf(')')" + form[5].ToString().IndexOf(")"));
                            facId = form[5].ToString().Substring(form[5].ToString().IndexOf('(')+1, 9);
                            System.Diagnostics.Debug.WriteLine("Admin create cancellation facId" + facId);
                            var addedItem = can.CreateCancellation(form[1], form[2], form[3], form[4], facId);
                            if (addedItem == null)
                            {
                                ViewBag.ExceptionMessage = "Could not create cancellation";
                                return View("Error");
                            }
                        }
                    }
                    else if (roles.GetRolesForUser(currentUserName).Contains("Faculty"))
                    {
                        if (form.Count == 5)
                        {
                            System.Diagnostics.Debug.WriteLine("form[0]" + form[0]);
                            System.Diagnostics.Debug.WriteLine("form[1]" + form[1]);
                            System.Diagnostics.Debug.WriteLine("form[2]" + form[2]);
                            System.Diagnostics.Debug.WriteLine("form[3]" + form[3]);
                            System.Diagnostics.Debug.WriteLine("form[4]" + form[4]);

                            facId = dc.Faculties.Find(currentUserId).FacultyId;
                            System.Diagnostics.Debug.WriteLine("Faculty create cancellation facId" + facId);
                            var addedItem = can.CreateCancellation(form[1], form[2], form[3], form[4], facId);
                            if (addedItem == null)
                            {
                                ViewBag.ExceptionMessage = "Could not create cancellation";
                                return View("Error");
                            }
                        }
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ViewBag.ExceptionMessage = e.Message;
                    return View("Error");
                }
            }
            else
            {
                return View("Error");
            }
        }
        [Authorize(Roles = "Admin, Faculty")]
        public ActionResult Edit(int? id)
        {
            //var currentUser = await faculty.FindByIdAsync(User.Identity.GetUserId());
            if (id == null)
            {
                ViewBag.ExceptionMessage = " Invalid record";
                return View("Error");
            }
            var cancellation = can.getCancellationFull(id);
            if (cancellation == null)
            {
                ViewBag.ExceptionMessage = "That record could not be edited because it doesn't exist";
                return View("Error");
            }
            /*if (cancellation.User.Id != currentUser.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }*/
            
            return View(cancellation);
        }
        [Authorize(Roles = "Admin, Faculty")]
        [HttpPost, ActionName("Edit")]

SchoolNotification/SchoolNotification/Views/Cancellation/Create.cshtml
@model SchoolNotification.ViewModels.CancellationCreate

@{
    ViewBag.Title = "Cancellation Create";
}

<h2>Create Cancellation</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CancellationCreate</legend>
        <p> @*ViewBag.currentUserName*@ </p>

        <p> @ViewBag.errMsg </p>

        <div class="editor-label">
            @Html.LabelFor(model => model.Course)
        </div>
        <div class="editor-field">
            @Html.DropDownList("courses")
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.DropDownList("dates")
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Message.Time)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message.Time)
            @Html.ValidationMessageFor(model => model.Message.Time)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Message)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message.MsgContent)
            @Html.ValidationMessageFor(model => model.Message.MsgContent)
        </div>
        @*if (ViewBag.facultyView == "Y") { 
            <div class="editor-label" >
                @Html.LabelFor(model => model.Faculty)
            </div>
            <div class="editor-label">
                @Html.EditorFor(model => model.Faculty.FirstName)
                @Html.ValidationMessageFor(model => model.Faculty.FirstName)
            </div>
        }*@
        @if (ViewBag.adminView == "Y")
        {
            <div class="editor-label">
                @Html.LabelFor(model => model.Faculty)
            </div>
            <div class="editor-label">
                @Html.DropDownList("faculties")
            </div>
        }
        
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolNotification/SchoolNotification/Views/Cancellation/Delete.cshtml
@model SchoolNotification.ViewModels.CancellationFull

@{
    ViewBag.Title = "Delete";
}

<h2>Cancellation Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>CancellationFull</legend>

    <table>
        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Date)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Date)
            </td>
        </tr>

        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Message.Time)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Message.Time)
            </td>
        </tr>

        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Course.CourseCode)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Course.CourseCode)
            </td>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Faculty.FacultyId)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Faculty.FacultyId)
            </td>
        </tr>

    </table>

</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SchoolNotification/SchoolNotification/Views/Cancellation/Details.cshtml
@model SchoolNotification.ViewModels.CancellationFull

@{
    ViewBag.Title = "Cancellation Details";
}

<h2>Cancellation Details</h2>

<fieldset>
    <legend>CancellationFull</legend>

    <table>
        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Date)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Date)
            </td>
        </tr>

        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Message.Time)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Message.Time)
            </td>
        </tr>

        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Course.CourseCode)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Course.CourseCode)
            </td>
        </tr>
        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Message.MsgContent)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Message.MsgContent)
            </td>
        </tr>

        <tr>
            <td class="display-label">
                @Html.DisplayNameFor(model => model.Faculty.FacultyId)
            </td>
            <td class="display-field">
                @Html.DisplayFor(model => model.Faculty.FacultyId)
            </td>
        </tr>
    </table>
</fieldset>
@if ((ViewBag.adminView == "Y") || (ViewBag.facultyView == "Y"))
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = ViewBag.id }) |
        @Html.ActionLink("Back to List", "Index", "Cancellation")
        
    </p>
}
else
{
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SchoolNotification/SchoolNotification/Views/Cancellation/Edit.cshtml
@model SchoolNotification.ViewModels.CancellationFull

@{
    ViewBag.Title = "Cancellation Edit";
}

<h2>Cancellation Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CancellationFull</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Message.Time)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message.Time)
            @Html.ValidationMessageFor(model => model.Message.Time)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Course.CourseCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Course.CourseCode)
            @Html.ValidationMessageFor(model => model.Course.CourseCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Message.MsgContent)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message.MsgContent)
            @Html.ValidationMessageFor(model => model.Message.MsgContent)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Faculty.FacultyId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Faculty.FacultyId)
            @Html.ValidationMessageFor(model => model.Faculty.FacultyId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolNotification/SchoolNotification/Views/Cancellation/Index.cshtml
@model IEnumerable<SchoolNotification.ViewModels.CancellationBase>

@{
    ViewBag.Title = "Cancellation Index";
}

<h2>Cancellation Index</h2>
@if ((ViewBag.facultyView == "Y") || (ViewBag.adminView == "Y"))
{
    if (ViewBag.adminView == "Y")
    { 
        using (Html.BeginForm("Index", "Cancellation", FormMethod.Get)){    
            <p> CourseCode: @Html.TextBox("SearchString") <br />   
            <input type="submit" value="Filter" /></p> 
        } 
    }
    
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>

            <th></th>
        </tr>

        @foreach (var item in ViewBag.canlist)
        {
            <tr>
                <td>
                    @item.Date
                </td>
                <td>
                    @item.Course.CourseCode
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                    @*Html.ActionLink("View Messages", "Index", "Message")*@
                    @Html.ActionLink(linkText: "View Messages", actionName: "Details", controllerName: "Message", routeValues: new { id = item.Id }, htmlAttributes: null)
                </td>
            </tr>
        }
    </table>
}
else if (ViewBag.studentView == "Y")
{
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>

            <th></th>
        </tr>
        @if (ViewBag.viewcan == true)
        {
            foreach (var item in ViewBag.canlist)
            {
            <tr>
                <td>
                    @item.Date
                </td>
                <td>
                    @item.Course.CourseCode
                </td>

                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("View Messages", "Index", "Message")
                </td>
            </tr>
            }
        }
        else
        {
            <tr><td>No Cancellation.</td><td></td><td></td></tr>
        }
    </table>
}
else
{
    <table><tr><td>You are not authorized to access cancellations.</td><td></td></tr></table>
}